spring.application.name=Udemy Project
project.image=images/

#LOCAL DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/ecomm
spring.datasource.username=postgres
spring.datasource.password=admin


# AWS DATABASE
#spring.datasource.url=jdbc:postgresql://ecomm.cu5wogumw3fp.us-east-1.rds.amazonaws.com:5432/ecomm
#spring.datasource.username=postgres
#spring.datasource.password=lazyuka1985

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.app.jwtSecret=mySecret123123f1hg3f4h1gf4h1g32f4h1gf4hg12f4hg1f4fg3f4g31hg34g1f4
spring.app.jwtExpirationMs=3000000
spring.app.jwtCookieName=springBootEcom


#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.org.example.udemyproject=DEBUG

#server.port=5000