spring.application.name=Udemy Project

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.app.jwtExpirationMs=86400000
spring.app.jwtCookieName=springBootEcom