app.storage.type=s3

project.image=/tmp/images/

aws.s3.bucket=dmitry-ecomm-images
aws.s3.region=us-east-1

spring.datasource.url=jdbc:postgresql://ecomm.cu5wogumw3fp.us-east-1.rds.amazonaws.com:5432/ecomm
spring.datasource.username=postgres
spring.datasource.password=lazyuka1985

spring.app.jwtSecret=rOIG3lC3NRTlYkGJRZw73BqYqAiNCvl0NG7WkJxOCfIRR3FFftCj0SNLOr80SXWirTI3xyvdME7ciH+QIrZjYg==

frontend.url=${FRONTEND_URL}

image.base.url=https://dmitry-ecomm-images.s3.us-east-1.amazonaws.com

stripe.secret.key=${STRIPE_SECRET_KEY}

server.port=5000