spring.application.name=Udemy Project
project.image=images/

#LOCAL DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/ecomm
spring.datasource.username=postgres
spring.datasource.password=admin


# AWS DATABASE
#spring.datasource.url=jdbc:postgresql://ecomm.cu5wogumw3fp.us-east-1.rds.amazonaws.com:5432/ecomm
#spring.datasource.username=postgres
#spring.datasource.password=lazyuka1985

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.app.jwtSecret=rOIG3lC3NRTlYkGJRZw73BqYqAiNCvl0NG7WkJxOCfIRR3FFftCj0SNLOr80SXWirTI3xyvdME7ciH+QIrZjYg==
spring.app.jwtExpirationMs=86400000
spring.app.jwtCookieName=springBootEcom


#server.port=5000

frontend.url=http://localhost:5173
image.base.url=http://localhost:8080/images

#STRIPE KEY
stripe.secret.key=${STRIPE_SECRET_KEY}